title: Upterm
theme: jekyll-theme-architect
description: Instant Terminal Sharing
show_downloads: false
google_analytics: UA-155365325-1
github:
    public: true
    is_project_page: true
    repository_url: https://github.com/owenthereal/upterm
    repository_nwo: owenthereal/upterm
    is_user_page: false
    owner_url: https://github.com/owenthereal
    owner_name: owenthereal
plugins:
    - jemoji
